### ISSUE TITLE
inittialize.init() fait planter le code

### ISSUE THREAD

**Issue by maxcolomb** [ArtiScales/MUPCity-OpenMOLE#2]
Comme je ne sais pas trop à quoi ça sert, je l'ai commenté, mais ça causera peut être des problèmes quand on voudra distribuer le code

**Comment by mbrasebin** [comment]
Corrigé, j'ai eu le problème par ailleurs, il semblerait que la méthode printRegistry soit soit très longue soit tourne dans le vide en enlevant ces appels, le problème semble corrigé. J'ai décommenté les différents appels Initialize et mis un main dans la classe pour s'assurer que ça fonctionne.

Cf commit : https://github.com/ArtiScales/MUPCity-OpenMOLE/commit/7aa3caae6e487f0c43bde38b5e638c2d33af054e
